### ISSUE TITLE
Horizontal scrollbar

### ISSUE THREAD

**Issue by mchelen** [carlvlewis/cvStrap-jsonresume#1]
I see a horizontal scrollbar on http://cv.carlvlewis.net/ in Firefox & Chrome. It doesn't actually allow scrolling, but it's still there. Any idea what causes this?

**Comment by carlvlewis** [comment]
Hey @mchelen -- weird. Can you screencap what you're seeing?

**Comment by carlvlewis** [comment]
@mchelen Are you on mobile? It does allow you to move to the padding space on each side in mobile viewports. The width of the container should probably be adjusted to prevent this.

**Comment by carlvlewis** [comment]
Okay, @mchelen, I see what you're referring to. Yes, because I very much wanted to use Bootstrap 2 for style reasons (despite it being non-responsive), I had to incorporate my own responsive stylesheets that are a little wider than the actual size of the container. I'll fix now.

Thanks for pointing out!

**Comment by carlvlewis** [comment]
To clarify, Bootstrap 2.0.3 is responsive but the size of my containers weren't set to be fluid.

**Comment by carlvlewis** [comment]
^^ that was for printing-ease.

**Comment by mchelen** [comment]
Yup to confirm, this is with desktop browsers.
IDK if it helps, but a quick hack that seemed to fix the issue was disabling the explicit `overflow: scroll;` on the `body` element. This removed the horizontal scrollbar, without affecting the vertical scrollbar.

**Comment by carlvlewis** [comment]
Awesome tip, Michael. Making that change now. And while I'm pretty sure I'll be able to add the theme to the registry via NPM, won't hesitate to reach out to you.

I'll clarify the documentation too (I, too, originally had publish.html files being spit out!)

**Comment by carlvlewis** [comment]
Hey, so, duh, was able to fix it simply by defining which of the two scrollbars I wanted to disable: 

```
overflow-y: scroll;
overflow-x: hidden;
```

**Comment by carlvlewis** [comment]
Also, one thing making the viewport wider (and thus scrolling) were the full URLs under the publications headings. Changed them to shortlinks and now all is good.

**Comment by mchelen** [comment]
Yup, that fixed it!
