### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by mchelen** [carlvlewis/cvStrap-jsonresume#5]
What method are you using to install & use the theme? Usually themes have an `index.js` which is called by `resume export` but I don't see one.

**Comment by carlvlewis** [comment]
Is that not in the JS directory? Lemme check. I had it there at one point at least.

**Comment by carlvlewis** [comment]
Got left out on an earlier commit. Now back.

**Comment by mchelen** [comment]
Ok cool, do you have a working copy of `package.json`? The one in the repo is blank. Edit: I made one here if it helps: https://github.com/mchelen/cvStrap-jsonresume/blob/master/package.json

Also the `index.js` points to `/style.css` and `/resume.template` but neither of those files exist in that location.

I'm curious what method you are currently using to generate the output?
